"use client"
import type { Metadata } from 'next'
import { Inter, Jost } from 'next/font/google'
import './globals.css'
import { Provider } from 'react-redux'
import { store } from '@/store/store'
import { useAppDispatch } from './hooks/redux'
import { useEffect } from 'react'
import { handleFechVersion } from '@/store/slices/version'

const inter = Jost({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children}: { children: React.ReactNode}) {
  
  return (
    <html lang="en">
      <Provider store={store} >

        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  )
}
